import type { NextPage } from "next";
import Head from "next/head";
import { Layout } from "~/components/Layout/Layout.component";
import { NextPageWithLayout } from "~/types/common.types";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>DaftAcademy - WebApp 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>DaftAcademy - WebApp 2022</p>
      </main>
    </>
  );
};

Home.getLayout = (page) => {
  return <Layout>{page}</Layout>
}

export default Home;
